config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :stores do
    resources :products, only: [:index, :show, :edit, :update, :new, :create, :destroy]
    get 'orders', to: 'orders#store_orders', as: :store_orders
    member do
      get 'orders/new', to: 'stores#new_order'
    end
  end
  
  scope :buyers do
    resources :orders, only: [:index, :create, :update, :destroy]
  end

  resources :orders, only: [:show] do
    member do
      put :accept
      put :dispatch_order
      put :complete
      put :cancel
    end
  end

  root to: "welcome#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "me" => "registrations#me"
  post "new" => "registrations#create", as: :create_registration
  post "sign_in" => "registrations#sign_in"

  get "listing" => "products#listing"
  get '/products/:id', to: 'products#redirect_to_store_product'

  post "search", to: "search#index"

  get 'dashboard/:id', to: 'stores#store_daily_revenue'
end

app/models/store.rb
class Store < ApplicationRecord
    acts_as_paranoid
    searchkick word_start: [:name], text_middle: [:name]

    belongs_to :user
    before_validation :ensure_seller
    has_many :products, dependent: :destroy
    has_many :orders
    has_one_attached :image
    scope :visible, -> { where(hidden: false) }
    validates :name, presence: true, length: {minimum: 3}

    def thumbnail
        image.variant(resize_to_limit: [100, 100]).processed { |v| v.quality(50) }
    end
    
    def medium
        image.variant(resize_to_limit: [200, 200]).processed { |v| v.quality(70) }
    end

    def image_with_default
      if image.attached?
        image
      else
        nil
      end
    end

    private

    def ensure_seller
        self.user = nil if self.user && !self.user.seller?
    end

    def search_data
      {
        name: name,
        hidden: hidden,
        user_id: user_id
      }
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  skip_forgery_protection only: %i[create update destroy]
  before_action :authenticate!
  before_action :set_store, only: %i[ show edit update destroy new_order store_daily_revenue]
  before_action :redirect_if_not_admin_or_owner, only: [:edit, :update, :destroy]
  before_action :redirect_if_not_store_owner, only: [:show]

  # GET /stores or /stores.json
  def index
    page = params.fetch(:page, 1)
    user = current_user()
    if user.admin?
      @stores = Store.includes(:image_attachment => :blob) 
    elsif user.buyer?
      @stores = Store.visible.includes(:image_attachment => :blob) 
    else
      @stores = Store.includes(:image_attachment => :blob).where(user: user[:id])
    end
    @stores = @stores.page(page)
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    if current_user.buyer?
      respond_to do |format|
        format.html { redirect_to stores_url, notice: "Unauthorized" }
        format.json { head :unauthorized }
      end
    end

    @store = Store.new
    
    if current_user.admin?
      @sellers = User.where(role: :seller)
    end
  end

  # GET /stores/:id/orders/new   form: POST => buyers/orders
  def new_order
    if current_user.admin?
      @order = Order.new
      @products = Product.visible.not_expired.where(store:@store)
      @buyers = User.where(role: :buyer)
    else
      respond_to do |format|
        format.html { redirect_to store_path(@store), alert: "Unauthorized" }
        format.json { head :unauthorized }
      end
    end
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  def create
    @store = Store.new(store_params)
    if !current_user.admin?
      @store.user = current_user
    end

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  def update
    
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  def destroy

    ActiveRecord::Base.transaction do
      @store.destroy!
    end

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def store_daily_revenue
    unless current_user.admin? || current_user == @store.user
      render json: { error: "Unauthorized" }, status: :unauthorized
      return
    end

    revenue = Order.joins(:order_items)
                .where('orders.created_at >= ? AND orders.store_id = ?', 30.days.ago, @store.id)
                .group_by_day('orders.created_at')
                .sum('order_items.price * order_items.amount')

    render json: {data: revenue }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store

      if action_name == "new_order"
        @store = Store.visible.find(params[:id])
      else
        @store  = if current_user.buyer?
                    Store.visible.includes(:image_attachment => :blob).find(params[:id])
                  else
                    Store.includes(:image_attachment => :blob).find(params[:id])
                  end
      end
      

      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { render 'stores/store_not_found', status: :not_found }
          format.json { render 'stores/store_not_found', status: :not_found }
        end
    end

    def redirect_if_not_admin_or_owner
      return if current_user == @store.user || current_user.admin?
  
      respond_to do |format|
        format.html { redirect_to stores_url, alert: "User doesn't match with store Owner" }
        format.json { render json: {error: "Unauthorized"}, status: :unauthorized }
      end
    end

    def redirect_if_not_store_owner
      return unless current_user.seller? && current_user != @store.user
  
      respond_to do |format|
        format.html { redirect_to stores_url, alert: "User doesn't match with store Owner" }
        format.json { render json: {error: "Unauthorized"}, status: :unauthorized }
      end
    end

    def store_params
      required = params.require(:store)
      if current_user.admin?
        required.permit(:name, :user_id, :hidden, :image)
      else
        required.permit(:name, :hidden, :image)
      end
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, multipart: true) do |form| %>
  <% if store.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
      <h2 class="font-bold"><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex items-center mb-4">
    <div class="mr-4 logo">
      <% if store.image.present? %>
        <%= image_tag store.image_with_default, class: "w-24 h-24 rounded-md" %>
      <% else %>
        <%= image_tag "shop-default-256.png", class: "w-24 h-24 rounded-md" %>
      <% end %>
    </div>

    <div class="flex flex-col">
      <div class="mb-2">
        <%= form.label :name, class: "block font-bold mb-1" %>
        <%= form.text_field :name, class: "form-input" %>
      </div>
      <div class="mb-2">
        <%= form.check_box :hidden, class: "form-checkbox h-5 w-5" %>
        <%= form.label :hidden, "Hidden", class: "text-sm font-medium text-gray-700" %>
      </div>
    </div>
  </div>

  <% if current_user.admin? && @sellers.present? %>
    <div class="mb-4">
      <%= form.label :seller, class: "block font-bold mb-1" %>
      <%= form.collection_select :user_id, @sellers, :id, :email, prompt: "Select a Seller", class: "form-select" %>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :image, class: "block font-bold mb-1" %>
    <%= form.file_field :image, class: "form-input" %>
  </div>

  <div>
    <%= form.submit store.persisted? ? "Update Store" : "Create Store", class: "btn-form" %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">

    <div>
      <div class="inline-flex items-center space-x-4">
        <div class="logo">
          <% if store.image.present? %>
            <%= image_tag store.image_with_default, class: "w-24 h-24" %>
          <% else %>
            <%= image_tag "shop-default-256.png", class: "w-24 h-24" %>
          <% end %>
        </div>
        <div class="truncate font-bold" style="max-width: 150px;">
          <p><%= store.name %></p>
        </div>
      </div>
    </div>
</div>

app/views/stores/edit.html.erb
<% if notice %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded-md mb-4">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
    <p><%= alert %></p>
  </div>
<% end %>

<div class="content-container">  
  <div>
    <h1>Editing store</h1>
  
    <%= render "form", store: @store %>
  </div>
  
  <br>
  
  <div>
    <%= link_to "Show this store", @store, class: "mr-2", style: "white-space: nowrap;" %>|
    <%= link_to "Back to stores", stores_path, style: "white-space: nowrap;" %>
  </div>
</div>

app/views/stores/index.html.erb
<% if notice %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded-md mb-4">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
    <p><%= alert %></p>
  </div>
<% end %>

<div class="content-container mb-1">
  <h1>Stores</h1>
  <p><%= link_to "New store", new_store_path %></p>
</div>

<div class="absolute left-0 right-0 content-container mt-4 mb-4">
    <%= paginate @stores %>
</div>

<div id="stores" class="relative mt-28">
  <% if @stores.any? %>
    <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-3 gap-y-4">
      <% @stores.each do |store| %>
        <div class="mt-4 content-container">
          <%= render store %>
          <p>
            <%= link_to "Show this store", store %>
          </p>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="mt-4 content-container">
      <p>Empty</p>
    </div>
  <% end %>
</div>


<div class="absolute left-0 right-0 content-container mt-4 mb-4">
    <%= paginate @stores %>
</div>

app/views/stores/new.html.erb
<div class="content-container">
  <h1>New store</h1>
  <%= render "form", store: @store %>
  <div>
    <%= link_to "Back to stores", stores_path %>
  </div>
</div>

app/views/stores/new_order.html.erb
<div class="content-container p-6 bg-white shadow-md rounded-lg">
  <h1 class="text-2xl font-bold mb-4">New Order</h1>

  <%= form_with(model: @order, url: orders_path, local: true) do |f| %>
    
    <% if flash[:alert].present? %>
      <p class="text-red-500 mb-4"><%= flash[:alert] %></p>
    <% end %>

    <div>
      <%= f.hidden_field :store_id, value: @store.id %>
    </div>

    <% if current_user.admin? %>
      <div class="mb-4">
        <%= f.label :buyer_id, "Select Buyer", class: "block font-bold mb-1" %>
        <%= f.collection_select :buyer_id, @buyers, :id, :email, { prompt: "Choose a Buyer" }, class: "form-select mt-1 block w-full" %>
      </div>
    <% end %>

    <div id="order_items" class="mb-4">
      <h3 class="text-xl font-semibold mb-2">Cart</h3>
      <% @order.order_items.each_with_index do |item, index| %>
        <div class="order_item mb-4 p-4 border rounded-lg">
          <%= f.fields_for "order_items[]", item do |item_fields| %>
            <%= item_fields.hidden_field :id %>
            <div class="mb-2">
              <%= item_fields.label :product_id, "Product", class: "block font-bold mb-1" %>
              <%= item_fields.collection_select :product_id, @products, :id, :title, { prompt: "Choose a Product" }, class: "form-select mt-1 block w-full" %>
            </div>
            <div class="mb-2">
              <%= item_fields.label :amount, "Amount", class: "block font-bold mb-1" %>
              <%= item_fields.number_field :amount, min: 1, class: "form-input mt-1 block w-full" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="mb-4">
      <button type="button" id="add-item-button" class="btn-form">Add Another Product</button>
    </div>

    <div>
      <%= f.submit "Create Order", class: "btn-form" %>
    </div>
  <% end %>
</div>





<script>
  function addProductItem() {
    let orderItemsDiv = document.getElementById('order_items');
    if (!orderItemsDiv) return;

    let newItem = document.createElement('div');
    newItem.classList.add('order_item');

    let timestamp = new Date().getTime();

    newItem.innerHTML = `
      <label for="order_order_items_${timestamp}_product_id">Product</label>
      <select name="order[order_items][][product_id]" id="order_order_items_${timestamp}_product_id">
        <option value="">Choose a Product</option>
        <% @products.each do |product| %>
          <option value="<%= product.id %>"><%= product.title %></option>
        <% end %>
      </select>
      <label for="order_order_items_${timestamp}_amount">Amount</label>
      <input type="number" name="order[order_items][][amount]" id="order_order_items_${timestamp}_amount" min="1" />
    `;

    orderItemsDiv.appendChild(newItem);
  }

  function setupAddItemButton() {
    let addItemButton = document.getElementById('add-item-button');
    if (addItemButton) {
      addItemButton.addEventListener('click', addProductItem);
    }
  }

  document.addEventListener('turbo:load', function() {
    console.log("turbo:load event fired");
    setupAddItemButton();
  });
</script>

app/views/stores/show.html.erb
<% if notice %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded-md mb-4">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
    <p><%= alert %></p>
  </div>
<% end %>

<div class="content-container">
  <%= render @store %>
  <% if current_user.admin? || current_user.eql?(@store.user)%>
    <%= link_to "Edit", edit_store_path(@store) %> |
  <% end %>

  <%= link_to "Back to stores", stores_path %>
  
  <% if current_user.admin? || current_user.eql?(@store.user) %>
    <%= button_to "Delete", @store, method: :delete, class: "btn-delete" %>
  <% end %>
</div>

<div class="content-container mt-4">
  <h3>Products</h3>
  
  <p><%= link_to "Show Products", store_products_path(@store) %></p>

  <% if current_user.admin? || current_user.eql?(@store.user)%>
    <p><%= link_to "New Product", new_store_product_path(@store) %></p>
  <% end %>
  <hr />
  <h3>Orders</h3>

  <p><%= link_to "Show Orders", store_store_orders_path(@store) %></p>
  <% if current_user.admin? %>
    <p><%= link_to "New Order", orders_new_store_path(@store) %></p>
  <% end %>
  </div>
</div>

app/views/stores/store_not_found.html.erb
<div class="content-container">
  <h3>Store not found.</h3></br>
  <%= link_to "Back to stores", stores_path %>
</div>