config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :stores do
    resources :products, only: [:index, :show, :edit, :update, :new, :create, :destroy]
    get 'orders', to: 'orders#store_orders', as: :store_orders
    member do
      get 'orders/new', to: 'stores#new_order'
    end
  end
  
  scope :buyers do
    resources :orders, only: [:index, :create, :update, :destroy]
  end

  resources :orders, only: [:show] do
    member do
      put :accept
      put :dispatch_order
      put :complete
      put :cancel
    end
  end

  root to: "welcome#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "me" => "registrations#me"
  post "new" => "registrations#create", as: :create_registration
  post "sign_in" => "registrations#sign_in"

  get "listing" => "products#listing"
  get '/products/:id', to: 'products#redirect_to_store_product'

  post "search", to: "search#index"

  get 'dashboard/:id', to: 'stores#store_daily_revenue'
end

app/models/product.rb
class Product < ApplicationRecord
  include Expirable
  acts_as_paranoid
  
  belongs_to :store
  searchkick word_start: [:title], text_middle: [:title]
  before_save :set_hidden_if_priceless
  scope :visible, -> { where(hidden: false) }
  scope :not_expired, -> { where(expired: false) }
  validates :title, presence: true, length: {minimum: 1}
  has_one_attached :image
  has_many :orders, through: :order_items

  def thumbnail
    image.variant(resize_to_limit: [100, 100]).processed { |v| v.quality(50) }
  end

  def medium
    image.variant(resize_to_limit: [200, 200]).processed { |v| v.quality(70) }
  end

  def image_with_default
    if image.attached?
      image
    else
      nil
    end
  end

  def set_hidden_if_priceless
    return if self.hidden == true
    self.hidden = !(price.present? && price > 0)
  end

  def search_data
    {
      title: title,
      hidden: hidden,
      expired: expired,
      store_hidden: store.hidden,
      store_user_id: store.user_id
    }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	skip_forgery_protection only: %i[create update destroy]

	before_action :authenticate!

	before_action :set_store, except: %i[listing redirect_to_store_product]
	before_action :set_product, only: %i[show edit update destroy redirect_to_store_product]

	before_action :authorize_admin, only: %i[listing]
	before_action :authorize_store_owner_and_admin, only: %i[create new edit update destroy]
	before_action :authorize_buyer_store_owner_and_admin, only: %i[show index]

  # GET /listing
	def listing
		page = params.fetch(:page, 1)

		@products = Product.includes(:store, :image_attachment => :blob)
		@products = @products.not_expired
		@products = @products.page(page)
	end

  # GET store/1/products/1 or store/1/products/1.json
	def show
		if @product.store_id != @store.id
			respond_to do |format|
				format.html { redirect_to store_products_path(@store), alert: "Product is not from this store." }
				format.json { render json: { error: { message: "Product is not from this store." }}, status: :unprocessable_entity }
			end
			return
		end

		respond_to do |format|
			format.html
			format.json { render :show, status: :created, location: store_product_url(@store, @product) }
		end
	end

  # GET /store/1/products or /store/1/products.json
	def index
		page = params.fetch(:page, 1)

		@products = @store.products.not_expired.includes(image_attachment: :blob)
		@products = @products.visible if current_user.buyer?
		@products = @products.page(page)
	end

  # GET /store/1/products/new
	def new
		@product = Product.new(store: @store)
	end

  # GET /store/1/products/1.edit
	def edit
	end

  # POST store/1/products
	def create
		@product = @store.products.new(product_params)

		respond_to do |format|
			if @product.save
				format.html { redirect_to store_products_path(@store), notice: "Product was successfully created." }
				format.json { render :show, status: :created, location: store_product_url(@store, @product) }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

  # PATCH/PUT store/1/products/1
	def update

		respond_to do |format|
			if @product.update(product_params)
				format.html { redirect_to store_products_path(@product.store), notice: "Product was successfully updated." }
				format.json { render :show, status: :ok, location: store_product_url(@store, @product) }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

  # DELETE store/1/products/1
	def destroy
		@product.destroy!

		respond_to do |format|
			format.html { redirect_to store_products_path(@product.store), notice: "Product was successfully updated." }
			format.json { head :no_content }
		end
	end

	def set_product
		@product =	if current_user.buyer?
						Product.visible.not_expired.includes(:image_attachment => :blob).find(params[:id])
					else
						Product.not_expired.includes(:image_attachment => :blob).find(params[:id])
					end
	rescue ActiveRecord::RecordNotFound
		respond_to do |format|
			format.html { render 'products/product_not_found', status: :not_found }
			format.json { render 'products/product_not_found', status: :not_found }
		end
	end

  #get '/products/:id' => redirect_to ''stores/:store_id/products/:id'
	def redirect_to_store_product
		@store = @product.store

		redirect_to store_product_path(@store, @product)
	end

	private

  # Use callbacks to share common setup or constraints between actions.
	def set_store
		@store= if current_user.buyer?
					Store.visible.find(params[:store_id])
				else
					Store.find(params[:store_id])
				end
	rescue ActiveRecord::RecordNotFound
		respond_to do |format|
			format.html { render 'stores/store_not_found', status: :not_found }
			format.json { render 'stores/store_not_found', status: :not_found }
		end
	end

	def authorize_store_owner_and_admin
		return if current_user == @store.user || current_user.admin?

		respond_to do |format|
			format.html { redirect_to stores_url, alert: "User doesn't match with store Owner." }
			format.json { render json: { error: "Unauthorized" }, status: :unauthorized }
		end
	end

	def authorize_buyer_store_owner_and_admin
		return if current_user.buyer? || current_user.admin?
		return if current_user == @store.user

		respond_to do |format|
			format.html { redirect_to stores_url, alert: "User doesn't match with store Owner." }
			format.json { render json: { error: "Unauthorized" }, status: :unauthorized }
		end
	end

	def authorize_admin
		return if current_user.admin?

		respond_to do |format|
			format.html do
			flash[:alert] = "Unauthorized."
			redirect_to stores_path
			end
			format.json { render json: { error: "Unauthorized." }, status: :unauthorized }
		end
	end

	def product_params
		params.require(:product).permit(:title, :price, :hidden, :image, :expires_in)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: [@store, @product], multipart: true) do |form| %>
  <% if @product.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
      <h2 class="font-bold"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex items-center mb-4">
    <div class="mr-4 logo">
      <% if @product.image.present? %>
        <%= image_tag @product.image_with_default, class: "w-24 h-24 rounded-md" %>
      <% else %>
        <%= image_tag "dish-default-256.png", class: "w-24 h-24 rounded-md" %>
      <% end %>
    </div>
    
    <div class="flex flex-col">
      <div class="mb-2">
        <%= form.label :title, class: "block font-bold mb-1" %>
        <%= form.text_field :title, class: "form-input" %>
      </div>
      <div class="mb-2">
        <%= form.check_box :hidden, class: "form-checkbox h-5 w-5" %>
        <%= form.label :hidden, "Hidden", class: "text-sm font-medium text-gray-700" %>
      </div>
      <div class="mb-2">
        <%= form.label :price, class: "block font-bold mb-1" %>
        <%= form.text_field :price, class: "form-input" %>
      </div>
      <div class="mb-2">
        <%= form.label :expires_in, class: "block font-bold mb-1" %>
        <%= form.select :expires_in, 
          [['never', 0],['5 seconds', 5],['1 hour', 3600],['2 hours', 7200],['6 minutes', 1800],['1 day', 86400]],class: "form-input" %>
      </div>
    </div>
  </div>

  <div class="mb-4">
    <%= form.label :image, class: "block font-bold mb-1" %>
    <%= form.file_field :image, class: "form-input" %>
  </div>  

  <div>
    <%= form.submit product.persisted? ? "Update Product" : "Create Product", class: "btn-form" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="mb-4">
  <div class="inline-flex items-start space-x-4 w-full">
    <div class="logo">
      <% if product.image.present? %>
        <%= image_tag product.image_with_default, class: "w-24 h-24", alt: product.title %>
      <% else %>
        <%= image_tag "dish-default-256.png", class: "w-24 h-24", alt: "Default Shop Image" %>
      <% end %>
    </div>
    <div class="flex-1 min-w-0">
      <h4 class="font-bold text-lg m-0 truncate"  style="max-width: 150px;"><%= product.title %></h4>
      <p class="text-gray-700 mt-1 mb-1">Price: <%= number_to_currency(product.price) %></p>
      <% if defined?(show_store_link) %>
        <p class="text-gray-700 mt-1 mb-1">Store: <%= link_to product.store.name, store_path(product.store), class: "text-blue-500 hover:underline" %></p>
      <% end %>
      <% if product.hidden %>
        <p class="text-gray-700 mt-1 mb-1">Hidden</p>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="content-container">
  <p style="color: red"><%= alert %></p>
  
  <h1>Editing Product</h1>
  
  <%= render "form", product: @product, store: @store %>
  <br>
  
  <div>
    <%= link_to "Show this product", store_product_path(@store, @product), class: "mr-2", style: "white-space: nowrap;" %> |
    <%= link_to "Back to stores", stores_path, style: "white-space: nowrap;"%>
  </div>
</div>

app/views/products/index.html.erb
 <% if notice %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded-md mb-4">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
    <p><%= alert %></p>
  </div>
<% end %>

<div class="content-container mb-1">
  <%= turbo_stream_from "products" %>
  <h1>Products</h1>
  <% if current_user.admin? || current_user.eql?(@store.user)%>
    <p><%= link_to "New Product", new_store_product_path(@store) %></p>
  <% end %>
</div>
  
<div class="absolute left-0 right-0 content-container mt-4 mb-4">
  <%= paginate @products %>
</div>

<div class="relative mt-28">
  <% if @products.any? %>
  <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-3 gap-y-4">
      <% @products.each do |product| %>
        <div class="content-container mt-4" id="<%= dom_id(product) %>">
          <%= render partial: "products/product", locals: { product: product } %>
          <p><%= link_to "Show this product", store_product_path(@store, product) %></p> 
        </div>
      <% end %>
    </div>
  <% else %>
  <div class="content-container mt-4">
    <p>Empty</p>
  </div>
  <% end %>
</div>

<div class="absolute left-0 right-0 content-container mt-4 mb-4">
  <%= paginate @products %>
</div>

app/views/products/listing.html.erb
<div class="content-container">
    <h1>Products Listing</h1>
</div>

<div class="content-container mt-4 mb-4">
    <%= paginate @products %>
</div>

<div>
    <% @products.each do |product| %>
        <div class="content-container mt-4">
            <%= render partial: "products/product", locals: { product: product, show_store_link: true } %>
            
            <% if current_user.admin? || current_user == product.store.user %>
                <p><%= link_to "Show this product", store_product_path(product.store, product) %></p>
            <% end %>
        </div>
    <% end %>
</div>

<div class="content-container mt-4 mb-4">
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div class="content-container">
  <h1>New Product</h1>
  <%= render "form", product: @product, store: @store %>  
  <div>
    <%= link_to "Back to store", store_path(@store) %>
  </div>
</div>

app/views/products/product_not_found.html.erb
<div class="content-container">
  <h3>Product not found.</h3></br>
  
  <% if @store.present? %>
    <%= link_to "Back to store", store_products_path(@store) %>
  <% else %>
    <%= link_to "Back to Stores", stores_path %>
  <% end %>
  
</div>

app/views/products/show.html.erb
<% if notice %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded-md mb-4">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md mb-4">
    <p><%= alert %></p>
  </div>
<% end %>

<div class="content-container mt-4">
  <h3 class="text-xl font-bold mb-4">Product Details</h3>

  <%= render partial: "products/product", locals: { product: @product, show_store_link: true } %>

  <div id="<%= dom_id(@product) %>" class="mt-4">
    <% if current_user.admin? || current_user.eql?(@product.store.user) %>
      <div>
        <%= link_to "Edit", edit_store_product_path(@product.store, @product) %>
        <%= button_to "Delete", store_product_path(@product.store, @product), method: :delete, data: { confirm: 'Are you sure you want to delete this product?' }, class: "btn-delete" %>
      </div>
    <% end %>
  </div>
</div>